version: '3'
services:
    webserver:
        container_name: php-apache
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./src:/var/www/html/
        ports:
            - 8000:80